package com.app.foodfinder.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * This class represents a Review entity.
 * It uses Lombok annotations to generate getters, setters, constructors, equals/hashcode and toString methods at compile-time.
 *
 * NOTE: Here, Spring Data JPA/Hibernate is used only to fetch results from the database(so table mapping is required) and not creating a schema.
 *       This has been disabled in application.properties file.
 *
 * @author CSC8019_Team 15
 * @since 2023-05-01
 */
@Data
@NoArgsConstructor
@Entity
@Table(name = "review")
public class Review {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "rating")
    private Double rating;

    @Column(name = "comment")
    private String comment;

    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    @ManyToOne
    @JoinColumn(name = "restaurant_id")
    private Restaurant restaurant;



    /**
     * Constructs a Review object with comment, rating, user and restaurant.
     * ID is not included as it is  auto-generated by the database.
     *
     * @param comment Review comment
     * @param rating Review rating
     * @param user User object of the user who submitted the review
     * @param restaurant Restaurant object of the restaurant that is being review for
     */
    public Review(Double rating, String comment, User user, Restaurant restaurant)
    {
        this.rating = rating;
        this.comment = comment;
        this.user = user;
        this.restaurant = restaurant;
    }



}
